/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OperationObjectPageObjectPage journey");

        opaTest("Navigate to OperationObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheSessionObjectPageGenerated.iSeeThisPage();
            Then.onTheSessionObjectPageGenerated.onTable({ property: "_Operations" }).iCheckRows();
            When.onTheSessionObjectPageGenerated.onTable({ property: "_Operations" }).iPressRow(0);

            Then.onTheOperationObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "OpHeader" });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "_OpHeader",
                field: "ManufacturingOrder",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "_OpHeader",
                field: "ManufacturingOrderOperation",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "_OpHeader",
                field: "ProductDescription",
                targetAnnotation: ""
            });
            Then.onTheOperationObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "_OpHeader",
                field: "Material",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheOperationObjectPageGenerated.iCheckNumberOfSections(6);
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("OpDetails");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "OpDetails" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "OperationDescription" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "OperationControlProfile" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "RelevantWorkCenterCode" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "WorkCenterID" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "OpDetails" }).iCheckField({ property: "Plant" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Quantities");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Quantities" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Quantities" }).iCheckField({ property: "OperationQuantity" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Quantities" }).iCheckField({ property: "ConfirmedYieldQty" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Quantities" }).iCheckField({ property: "ConfirmedScrapQty" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Dates");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Dates" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ErlstSchedldExecStrtTstmp" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "SchedldDurationSeconds" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ActualExecutionStartTstmp" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ActualExecutionEndTstmp" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Dates" }).iCheckField({ property: "ActualDurationSeconds" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("StdValues");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "StdValues" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "StdValues" }).iCheckField({ property: "WorkCenterStandardWorkQty1" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "StdValues" }).iCheckField({ property: "WorkCenterStandardWorkQty2" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "StdValues" }).iCheckField({ property: "WorkCenterStandardWorkQty3" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Status");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Status" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "OperationIsMilestone" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "OperationIsReleased" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "OperationIsPartiallyConfirmed" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "OperationIsConfirmed" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "UserStatusShortText" });
            Then.onTheOperationObjectPageGenerated.onForm({ section: "Status" }).iCheckField({ property: "UserStatusText" });
            When.onTheOperationObjectPageGenerated.iPressSectionIconTabFilterButton("Components");
            Then.onTheOperationObjectPageGenerated.iCheckSection({ section: "Components" });
            Then.onTheOperationObjectPageGenerated.onTable({ property: "_Components" }).iCheckColumns(undefined, {"CompId":{"header":"Item Text"},"Material":{"header":"Material"},"MatlCompRequirementDate":{"header":"Requirement Date"},"RequiredQuantity":{"header":"Requirement Quantity"},"WithdrawnQuantity":{"header":"Withdrawn Quantity"},"StorageLocation":{"header":"Storage Location"},"Batch":{"header":"Batch"},"ReservationIsFinallyIssued":{"header":"Final Issue"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});