/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SessionObjectPageObjectPage journey");

        opaTest("Navigate to SessionObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheSessionObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header1" });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header1",
                field: "UserName",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header1",
                field: "UserFullName",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header2" });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header2",
                field: "PersNumber",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header2",
                field: "EmpFullName",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header3" });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header3",
                field: "WorkCenterId",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header3",
                field: "WorkCenterText",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header4" });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header4",
                field: "SessionStartDateTime",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header4",
                field: "WorkStart",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header4",
                field: "WorkEnd",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheSessionObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheSessionObjectPageGenerated.iPressSectionIconTabFilterButton("AppNavigation");
            Then.onTheSessionObjectPageGenerated.iCheckSection({ section: "AppNavigation" });
            Then.onTheSessionObjectPageGenerated.onTable({ property: "_AppNav" }).iCheckColumns(undefined, {"Title":{"header":"Alkalmazás"}});
            When.onTheSessionObjectPageGenerated.iPressSectionIconTabFilterButton("BatchItems");
            Then.onTheSessionObjectPageGenerated.iCheckSection({ section: "BatchItems" });
            Then.onTheSessionObjectPageGenerated.onTable({ property: "_Operations" }).iCheckColumns(undefined, {"ManufacturingOrderOperation":{"header":"Operation or Phase"},"ProductDescription":{"header":"Product Description"},"Material":{"header":"Material"},"OperationDescription":{"header":"Operation Text"},"OperationControlProfile":{"header":"Control Profile"},"RelevantWorkCenterCode":{"header":"Work Center"},"WorkCenterID":{"header":"Work Center"},"Plant":{"header":"Plant"},"OperationIsMilestone":{"header":"Milestone Indicator"},"OperationIsReleased":{"header":"ENGD"},"OperationIsPartiallyConfirmed":{"header":"RVJL"},"UserStatusShortText":{"header":"FelhStátusz"},"UserStatusText":{"header":"FelhStátusz"},"OperationQuantity":{"header":"Operation Quantity"},"ConfirmedYieldQty":{"header":"Confirmed Yield"},"ConfirmedScrapQty":{"header":"Confirmed Scrap"},"WorkCenterStandardWorkQty1":{"header":"Előkészületi idő"},"WorkCenterStandardWorkQty2":{"header":"Gépi idő"},"WorkCenterStandardWorkQty3":{"header":"Személyi idő"},"ErlstSchedldExecStrtTstmp":{"header":"Terv kezdés"},"SchedldDurationSeconds":{"header":"Terv időtartam (mp)"},"ActualExecutionStartTstmp":{"header":"Tényl. kezdés"},"ActualExecutionEndTstmp":{"header":"Tényl. befejezés"},"ActualDurationSeconds":{"header":"Tényl. időtartam (mp)"},"OrderOperationBarcode":{"header":"OrderOperationBarcode"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});